### ISSUE TITLE
PKTCategoryOption multiple options not supported?

### ISSUE THREAD

**Issue by BobDG** [podio/podio-objc#13]
Hi, I have a category field with multiple options but it seems the PKTCategoryOption only returns 1 value in the item? Not 2 or 3? How should this work?

**Comment by BobDG** [comment]
@romainbriche Not sure if you receive e-mails for new issues (in my Github I don't) so I'm mentioning you with my hope you'll get an e-mail :)

**Comment by BobDG** [comment]
Never mind, I found a way to make it work!

**Comment by romainbriche** [comment]
Hi @BobDG, sorry for the lack of reactivity. I was on holiday.
Glad that you figured that out 👍
