### ISSUE TITLE
Crash when trying to load a Phone field

### ISSUE THREAD

**Issue by foffer** [podio/podio-objc#14]
It seems that the framework does not support a Phone field.

We have an app where the phone number is defined in the phone field, and thus, a crash happens. Please refer to [this SO](http://stackoverflow.com/questions/37772392/crash-when-trying-to-load-data-via-pktitem) answer for stack trace and debug screenshots. Looking in the Framework it does indeed look like a phone field is not considered [PKTConstants](https://github.com/podio/podio-objc/blob/7efbc4296ffed4584ee402769b0eabb130c7c031/PodioKit/Common/Support/PKTConstants.h#L165)

**Comment by crochik** [comment]
The PR#15 (https://github.com/podio/podio-objc/pull/15) will address the crash. 
Please note that for now phone and email fields will mapped to PKTStringItemFieldValue class. In the future we may create specialized classes to handle them.
